mysql:
    url: "root:111111@tcp(127.0.0.1:3306)/go?charset=utf8"
    user: "root"
    password: "111111"
    host: "127.0.0.1"
    port: 3306
    db: "go"
    interval: 1
    expired: 1
log-level: info